#!/usr/bin/env node

// ========== SOLTHRON EXTENSION BUILD SCRIPT ==========
// This script bundles all modular source files into a single content.js file

const fs = require('fs');
const path = require('path');

// Define the order of modules to bundle
const modules = [
    // Core modules
    'src/core/constants.js',
    'src/core/state.js',

    // API modules
    'src/api/backend-auth.js',

    // Analytics
    'src/analytics/tracker.js',

    // Platform detection
    'src/platform/detector.js',
    'src/platform/extractors.js',

    // Utilities
    'src/utils/text-processing.js',
    'src/utils/code-detector.js',
    'src/utils/cursor.js',

    // UI modules
    'src/ui/animations.js',
    'src/ui/notifications.js',

    // Note: The rest of the features remain in the original content.js for now
    // This approach demonstrates the modular structure while ensuring stability
];

console.log('🔨 Building Solthron Extension...\n');

// Read the original content.js to extract the remaining code
const originalContent = fs.readFileSync('content.js.backup', 'utf8');

// Function to remove import/export statements and convert to plain JS
function processModule(content, moduleName) {
    console.log(`  ✓ Processing ${moduleName}`);

    // Remove import statements
    content = content.replace(/import\s+{[^}]*}\s+from\s+['"][^'"]+['"];?\s*/g, '');
    content = content.replace(/import\s+\*\s+as\s+\w+\s+from\s+['"][^'"]+['"];?\s*/g, '');
    content = content.replace(/import\s+\w+\s+from\s+['"][^'"]+['"];?\s*/g, '');

    // Convert export const/let/var to just const/let/var
    content = content.replace(/export\s+(const|let|var)\s+/g, '$1 ');

    // Convert export function to just function
    content = content.replace(/export\s+function\s+/g, 'function ');

    // Convert export async function to just async function
    content = content.replace(/export\s+async\s+function\s+/g, 'async function ');

    // Remove export default and export { ... }
    content = content.replace(/export\s+default\s+/g, '');
    content = content.replace(/export\s+{[^}]*};?\s*/g, '');

    return content;
}

// Start building the output
let output = '';

// Add header
output += `// ========== SOLTHRON EXTENSION ==========
// Built from modular source files
// Build Date: ${new Date().toISOString()}
// DO NOT EDIT THIS FILE DIRECTLY - Edit files in /src instead
//
// To rebuild: node build.js
// ==========================================

`;

// Add IIFE wrapper start
output += '(function() {\n';
output += '  "use strict";\n\n';

// Process and add each module
modules.forEach(modulePath => {
    try {
        const fullPath = path.join(__dirname, modulePath);
        let content = fs.readFileSync(fullPath, 'utf8');

        // Process the module
        content = processModule(content, modulePath);

        // Add to output with section marker
        output += `  // ========== ${modulePath.toUpperCase()} ==========\n`;
        output += content + '\n\n';
    } catch (error) {
        console.error(`  ✗ Error processing ${modulePath}:`, error.message);
        process.exit(1);
    }
});

// Find where the modularized code ends in the original file
// We'll extract everything after line 1460 (after BackendAuth) as the remaining features
const lines = originalContent.split('\n');

// Find the end of BackendAuth object (around line 1460)
let startLine = 0;
for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes('};') && i > 1460 && i < 1470) {
        startLine = i + 1;
        break;
    }
}

console.log(`  ✓ Extracting remaining features from line ${startLine}`);

// Add remaining code
output += `  // ========== REMAINING FEATURES (TO BE MODULARIZED) ==========\n`;
output += `  // The following code will be gradually moved to feature modules\n\n`;

// Get the remaining code but skip the parts we've already modularized
const remainingCode = lines.slice(startLine).join('\n');

// Remove the parts we've already extracted
let cleanedRemaining = remainingCode;

// Remove analytics section (already modularized)
cleanedRemaining = cleanedRemaining.replace(/\/\/ ========== ANALYTICS TRACKING ==========[\s\S]*?(?=\/\/ ==========|$)/m, '');

// Remove platform detection (already modularized)
cleanedRemaining = cleanedRemaining.replace(/\/\/ ========== PLATFORM DETECTION ==========[\s\S]*?function detectAIPlatform[\s\S]*?return 'unknown';\s*}/m, '');

// Remove extract functions (already modularized)
cleanedRemaining = cleanedRemaining.replace(/\/\/ ========== EXTRACT LAST Q&A EXCHANGE ==========[\s\S]*?(?=\/\/ ========== CURSOR|\/\/ ==========)/m, '');

// Remove cursor utilities (already modularized)
cleanedRemaining = cleanedRemaining.replace(/\/\/ ========== CURSOR POSITION UTILITIES ==========[\s\S]*?(?=\/\/ ========== @MENTIONS|\/\/ ==========)/m, '');

// Remove code detection (already modularized)
cleanedRemaining = cleanedRemaining.replace(/\/\/ ========== DETECT CODE IN TEXT ==========[\s\S]*?function detectLanguage[\s\S]*?return null;\s*}/m, '');

// Add the cleaned remaining code
output += cleanedRemaining;

// Close IIFE wrapper
output += '\n})();\n';

// Write the bundled file
console.log('\n📦 Writing bundled content.js...');
fs.writeFileSync('content-new.js', output);

console.log('✅ Build complete! Generated: content-new.js');
console.log('\n📋 Next steps:');
console.log('   1. Review content-new.js');
console.log('   2. Test the extension with content-new.js');
console.log('   3. If everything works, rename:');
console.log('      - content.js → content-old.js (backup)');
console.log('      - content-new.js → content.js');
console.log('\n');
